rayanfer32/nexus-explorer-next

- .eslintrc.json
added the eslint linterns to the code
> add eslint rules

- src/components/Footer/Footer.js
- src/components/Footer/Footer.module.css
- src/components/Layout/Layout.js
- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
- src/components/atoms/SearchBar/SearchBar.module.css
- src/components/atoms/SearchBar/SearchBarLong.js
- src/components/atoms/SearchBar/index.jsx
- src/components/atoms/ThemeMode/ThemeMode.module.css
- src/components/atoms/ThemeMode/index.jsx
- src/styles/globals.css
- Seach bar design update
- Them mode toggle design update
- none
- none
- none
|  |  |
> feat: style update add search & theme component

- src/components/Navbar/Navbar.module.css
- src/components/atoms/RTTable/RTTRow.jsx
- src/components/atoms/RTTable/RTTRow.module.css
> feat: 🎨 improve the txn table row

- src/components/atoms/RTTable/RTTRowBlock.jsx
- src/components/atoms/RTTable/RTTRowBlock.module.css
> style: 💄 improve table row style

- src/components/Layout/Layout.module.css
- src/components/Navbar/Navbar.module.css
- src/components/Panel1/Panel1.js
- src/components/Panel1/Panel1.module.css
- src/components/atoms/SmallCard/SmallCard.module.css
- src/components/atoms/SmallCard/index.jsx
- src/styles/globals.css
> refactor: pannel one responsive

- src/components/Panel3/Panel3.module.css
> revert: hide chart for small screen

- src/components/Footer/Footer.js
- src/components/Footer/Footer.module.css
- src/components/Layout/Layout.js
- src/components/Layout/Layout.module.css
- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.css
- src/pages/_document.js
- src/styles/globals.css
> fix: styles

- src/assets/index.js
- src/components/Footer/Footer.js
- src/components/Navbar/Navbar.js
- src/components/atoms/Loader/CircularLoader.jsx
- src/components/atoms/Loader/DotLoader.jsx
- src/components/atoms/Loader/Loader.module.scss
- src/components/atoms/Loader/index.jsx
- src/pages/test.js
- src/stories/components/Loader.stories.js
- src/types/footer.js
- src/types/index.js
- src/types/navbar.js
- src/types/strings.js
can be tested on route `/test`
- none
- none
- none
|  |  |
> feat: add component loader

- src/components/Panel3/Panel3.jsx
- src/components/atoms/Rail/index.jsx
- src/pages/_document.js
- src/pages/blocks.js
- src/pages/index.js
- src/pages/scan/[addr].js
- src/types/strings.js
> Api and bug fixes 

- src/components/Chart/ChartsApex.jsx
- src/components/Panel1/Panel1.js
- src/components/Panel2/Panel2.js
- src/components/atoms/NE_Shimmer/Shimmer.module.scss
- src/components/atoms/NE_Shimmer/index.jsx
- src/pages/test.js
- src/stories/components/Shimmer.stories.js
- src/styles/globals.css
> feat: replace loading with shimmer

- src/components/Navbar/Navbar.js
- src/components/Navbar/Navbar.module.scss
> sidebar: modify the style and event on click

- src/components/Chart/ApexPie.jsx
- src/components/Chart/ApexTest.jsx
- src/components/Chart/ChartsApex.jsx
- src/components/Navbar/Navbar.js
- src/components/atoms/InfoCard/index.jsx
- src/hooks/useDarkMode/useDarkMode.js
- src/pages/TestComponents/BlockEstimator.jsx
- src/pages/richlist.js
- src/pages/scan/[addr].js
- src/pages/test.js
- src/styles/richlist.module.scss
> feat: NXS distrubution chart & Transaction info page

- src/components/atoms/NE_Shimmer/Shimmer.module.scss
- src/components/atoms/NE_Shimmer/index.jsx
- src/stories/components/Shimmer.stories.js
- src/types/strings.js
> feat: 🎨 add sub category

- src/components/Toast/Toast.module.scss
- src/components/Toast/index.jsx
- src/components/atoms/InfoCard/index.jsx
- src/components/atoms/ToastMessage/ToastMessage.module.scss
- src/components/atoms/ToastMessage/index.jsx
- src/stories/components/ToastMessage.stories.js
- src/styles/globals.css
- src/types/index.js
- src/types/toastMessage.js
New component
support custom toast message 
- currently alert used
- added new component
- different type to component
- customisable component 
- added documentation 
- toast message display  position option is not supported currently
> feat: ✨ introduce custom toast  messager

- src/components/AccountInfo/AccountInfo.jsx
- src/components/Table/Table.jsx
- src/components/atoms/InfoCard/index.jsx
- src/components/atoms/SmallCard/index.jsx
- src/pages/index.js
- src/pages/scan/[addr].js
- src/pages/transactions.js
- src/types/constants.js
- src/utils/helper.js
> feat: SSG and collapsible Infocards

- package.json
> release 0.02

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
> chore: 📈 update template

- src/components/atoms/InfoCard/InfoCard.module.css
- src/components/atoms/InfoCard/index.jsx
- none
- none
- none
|  |  |
|  |  |
> 💄 fix mulitple contracts

- .github/labeler.yml
- .github/workflows/labeler.yml
This is experimental !!!
- none
- none
- none
|  |  |
|  |  |
> chore: 👷add labeler actions

- src/components/Footer/Footer.js
- src/pages/globalnames.jsx
- src/pages/richlist/index.js
- src/types/footer.js
- src/types/navbar.js
- none
- none
- none
|  |  |
|  |  |
> Added Globalnames page and moved about to footer

- src/components/Chart/ChartsApex.module.css
- src/components/Navbar/Navbar.module.scss
- src/components/Panel1/Panel1.js
- src/components/Table/DynamicPagination.jsx
- src/components/Table/Table.jsx
- src/components/atoms/CopyText/CopyText.jsx
- src/components/atoms/DetailCard/DetailCard.module.scss
- src/components/atoms/DetailCard/TypeOne.jsx
- src/components/atoms/DetailCard/TypeTwo.jsx
- src/components/atoms/DetailCard/index.jsx
- src/components/atoms/InfoCard/InfoCard.module.scss
- src/components/atoms/InfoCard/index.jsx
- src/components/atoms/SmallCard/SmallCard.module.scss
- src/pages/blocks.js
- src/pages/transactions.js
- src/styles/globals.css
- src/utils/helper.js
- none
- none
- none
|  |  |
|  |  |
> feat+style: Added Dynamic pagination for blocks and Transactions, subtle card borders

- src/components/Chart/ChartsApex.jsx
- src/components/Table/DynamicPagination.jsx
- src/pages/TestComponents/BlockEstimator.jsx
- src/pages/TestComponents/ChartApi.jsx
- src/pages/api/hello.js
- src/pages/scan/[addr].js
- src/pages/test.js
- src/pages/transactions.js
- src/styles/globals.css
- none
- none
- none
|  |  |
|  |  |
> Added local charting api support 

- src/hooks/useNetwork/useNetwork.jsx
- src/pages/about/index.js
- none
- none
- none
|  |  |
|  |  |
> feat+fix: increase api limit ,dynamically fetch contributors

- package.json
- src/components/Panel2/Panel2.js
- src/components/atoms/CopyText/CopyText.jsx
- src/components/atoms/RTTable/RTTable.module.scss
- src/styles/index.module.scss
- none
- none
- none
|  |  |
|  |  |
> prevent breaking of copy button, fix RTT table overflow

- src/components/Panel2/Panel2.js
- none
- none
- none
|  |  |
|  |  |
> 🐛 prevent going below 0

- src/components/atoms/InfoCard/InfoCard.module.scss
- none
- none
- none
|  |  |
|  |  |
> 💄 fix text color

- src/hooks/useNetwork/useNetwork.jsx
- none
- none
- none
|  |  |
|  |  |
> 🐛 fix: #98 Only query for NXS token

- .husky/post-merge
- package.json
- src/contexts/AppContext.js
- yarn.lock
- Added the package `js-cookie` 
- Support update of multiple app-context states
- support post-merge; run `yarn install` on `git pull` 
- none
- support post-merge 
- add new package to set/update/remoev cookies
- none
|  |  |
|  |  |
> chore: support multi app context update and added post-merge husky config

- src/components/Chart/ChartsApex.jsx
- src/components/atoms/NE_Card/NE_CompactCard/CompactCard.module.scss
- src/pages/metrics/styles.module.scss
- src/types/StringsTypes.js
- none
- none
- none
|  |  |
|  |  |
> fix+feat: update metrics, hide chart toolbar for mobile 

- src/components/Panel1/Panel1.js
- src/components/Panel2/Panel2.js
- src/components/Panel3/Panel3.jsx
- src/components/TestComponents/index.jsx
- src/components/atoms/NE_ErrorCard/ErrorCard.jsx
- src/pages/globalnames.jsx
- src/pages/metrics/index.js
- src/pages/namespaces.jsx
- src/pages/scan/[addr].js
- src/pages/tokens/index.jsx
- src/pages/trustlist/index.js
- none
- none
- none
|  |  |
|  |  |
> ✨ added Error Component

- src/components/Chart/ChartsApex.module.scss
ios safari donut chart misplace
- none
- none
- none
| ![image](https://user-images.githubusercontent.com/52356082/156594461-b557cefa-c6df-4ab3-8a12-26c6ab2aff37.png) | ![image](https://user-images.githubusercontent.com/52356082/156594577-94776bda-bd8b-4256-8541-8065d378eb82.png) |
|  |  |
> fix: chart misplace in safari ios

- src/components/atoms/DetailCard/DetailCard.module.scss
detail card background abstract style fix
- none
- none
- none
|  |  |
|  |  |
> fix: details card style

- src/components/Header/PageHeader/PageHeader.jsx
- src/components/Header/PageHeader/index.jsx
- src/pages/about/index.js
- src/pages/blocks.js
- src/pages/globalnames.jsx
- src/pages/metrics/index.js
- src/pages/namespaces.jsx
- src/pages/richlist/index.js
- src/pages/scan/[addr].js
- src/pages/tokens/index.jsx
- src/pages/transactions.js
- src/pages/trustlist/index.js
- src/types/PageMetaTypes.js
- src/types/index.js
padded the page title and description to each pages
- none
- none
- none
|  |  |
|  |  |
> feat: add page title and description

- src/components/UserAccount/AccountDetail/AccountDetail.jsx
- src/components/UserAccount/UserAccount.jsx
- src/components/atoms/NE_CopyText/CopyText.jsx
- src/pages/globalnames.jsx
- src/pages/transactions.js
- none
- none
- none
|  |  |
|  |  |
> 🐛 fix: Show Ellipsis  based on device

- src/components/UserAccount/AccountDetail/AccountDetail.jsx
- src/components/UserAccount/UserAccount.jsx
- src/components/atoms/NE_CopyText/CopyText.jsx
- src/hooks/useNetwork/useNetwork.jsx
- src/pages/globalnames.jsx
- src/pages/transactions.js
- src/utils/common/fetch.js
- none
- none
- none
|  |  |
|  |  |
> Cache less frequently updated pages 

- src/components/UserAccount/AccountDetail/AccountDetail.jsx
- src/components/UserAccount/AccountDetail/AccountDetail.module.scss
- src/components/UserAccount/UserAccount.jsx
- src/pages/blocks.js
- none
- none
- none
|  |  |
|  |  |
> 🐛 added stake rate, fix color for trust

- src/components/Header/PageHeader/PageHeader.jsx
- none
- none
- none
|  |  |
|  |  |
> feat: pass page title/description as optional prop

- src/components/UserAccount/AccountDetail/AccountDetail.module.scss
- none
- none
- none
|  |  |
|  |  |
> fix: account page detail bar improve

- src/components/Chart/ChartsApex.module.scss
- src/pages/richlist/richlist.module.scss
- none
- none
- none
|  |  |
|  |  |
> fix: double scroll appearance

- src/hooks/useNetwork/useNetwork.jsx
- src/types/ConstantsTypes.js
- src/types/FooterTypes.js
Avoid storing the link in context and caching it 
Update the discord community join invite link
- none
- none
- none
|  |  |
|  |  |
> fix: moveout links from app context

- src/components/UserAccount/AccountDetail/AccountDetail.jsx
- src/hooks/useNetwork/useNetwork.jsx
- none
- none
- none
|  |  |
|  |  |
> Show account name ,show only upto 20 recent transactions (reduce load on node)

- src/components/Header/Header.module.scss
- src/styles/globals.css
- none
- none
- none
|  |  |
|  |  |
> feat: header is stikcy to the top on scroll

- src/components/Panel2/Panel2.js
- none
- none
- none
|  |  |
|  |  |
> 👽️  fix: calc marketcap based on metrics total supply

- .github/labeler.yml
- .github/workflows/labeler.yml
- .husky/post-merge
- .prettierignore
- none
- none
- none
|  |  |
|  |  |
> fix: husky git hooks

- src/pages/scan/[addr].js
- src/types/ConstantsTypes.js
- none
- none
- none
|  |  |
|  |  |
> 🐛 fix: scan address api route

- .github/labeler.yml
Hotfix to the CI laberer 
- none
- none
- none
|  |  |
|  |  |
> pr labeler for .md file

- src/components/UserAccount/AccountInfo/AccountInfo.jsx
- src/utils/converter.js
- none
- none
- none
|  |  |
|  |  |
> ✨ Show USD conversions

- src/types/FooterTypes.js
- none
- none
- none
|  |  |
|  |  |
> 📝 Add link to nexus docs

- src/pages/about/index.js
- none
- none
- none
|  |  |
|  |  |
> ⚡️ fetch contributors statically

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_req.md
- .github/pull_request_template.md
- none
- none
- none
|  |  |
|  |  |
> revamp: update github issue/pr template

- src/utils/converter.js
- 
- none
- none
- none
|  |  |
|  |  |
> 💄 show three dots

- src/components/Table/DynamicPagination.jsx
- src/components/UserAccount/TransactionDetails/TransactionDetails.jsx
- src/components/UserAccount/TransactionDetails/TransactionDetails.module.scss
- src/components/UserAccount/UserAccount.jsx
- src/hooks/useNetwork/useNetwork.jsx
- 
- none
- none
- none
|  |  |
|  |  |
> Fix: Dynamic Pagination for Account and Trust Transaction Details

- src/components/Header/Header.jsx
- src/components/Header/Navbar/Navbar.jsx
- src/components/atoms/NE_Card/NE_SmallCard/index.jsx
- src/components/atoms/NE_ThemeMode/index.jsx
- src/contexts/AppContext.js
- src/hooks/useDarkMode/useDarkMode.js
-  mismatch in the theme toggler icon on initial load 
- none
- none
- none
|  |  |
|  |  |
> fix: initial theme toggle output icon

- src/hooks/useNetwork/useNetwork.jsx
- 
- none
- none
- none
|  |  |
|  |  |
> 🐛 Convert richlist api to post api

- src/components/atoms/NE_RTTable/NE_RTTRansactions/RTTransaction.jsx
- 
- none
- none
- none
|  |  |
|  |  |
> fix: txn_id to txid

- src/pages/index.js
- src/types/ConstantsTypes.js
-  Increase the server-side internal timings to 5min 
- none
- none
- none
|  |  |
|  |  |
>  increase ssg interval to 5 min

- src/components/Richlist/Richlist.jsx
- src/hooks/useNetwork/useNetwork.jsx
- src/pages/blocks.js
- src/pages/richlist/index.js
- src/utils/common/fetch.js
- 
- none
- none
- none
|  |  |
|  |  |
> ⚡️ Static ISR for Richlist

- src/pages/ambassador-dao/index.js
- src/pages/network/index.js
- src/types/NavbarTypes.js
-  add new page Ambassador Dao
- none
- none
- none
|  |  |
|  |  |
> feat: add new page ambassador dao

- src/components/common/NE_CopyText/CopyText.jsx
- src/components/common/NE_RTTable/NE_BlockData/BlockData.jsx
- src/components/common/NE_RTTable/NE_RTTRansactions/RTTransaction.jsx
- src/components/common/PushLink/index.jsx
-  custom link for dynamic route
- refactor where ever anchor tag is used replace with the custom link
- none
- none
- none
|  |  |
|  |  |
> feat: add new custom dynamic link

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_req.md
- .github/pull_request_template.md
- .github/release-drafter.yml
- .github/workflows/dangerjs.yml
- .github/workflows/release-drafter.yml
- .github/workflows/update-changelog.yml
- dangerfile.js
- package.json
- yarn.lock
-  refactor the workflows and template
- add the danger file to on pr raise
- none
- none
- none
|  |  |
|  |  |
> chore: add danger file and refactor workflows

- src/components/Views/Dao/dao.module.scss
- src/components/Views/Dao/index.jsx
> fix: add highlights & icons to links

- src/components/Views/Dao/Invoices/index.jsx
- src/components/Views/Dao/Invoices/invoices.module.scss
- src/hooks/useNetwork/useNetwork.jsx
> feat: add caching for invoices

- src/components/common/NE_ThemeMode/ThemeMode.module.scss
- src/components/common/NE_ThemeMode/index.jsx
- change theme toggle button for desktop
- none
- none
> feat: change theme toggle for desktop

- src/components/Views/Dao/InvoiceModal/index.jsx
- src/components/Views/Dao/Invoices/index.jsx
- src/components/common/PushLink/index.jsx
- src/pages/scan/index.js
> feat: invoice scan with standard url pattern

- .github/release-drafter.yml
> ci: Update release-drafter.yml

- src/components/Footer/Footer.jsx
- src/components/common/NE_Button/index.jsx
- src/components/common/NE_Card/NE_DetailCard/Basic/index.jsx
- src/components/common/NE_Card/NE_DetailCard/Market/index.jsx
- src/components/common/NE_Card/NE_DetailCard/index.jsx
- src/components/common/NE_Card/index.jsx
- src/components/common/NE_Dropdown/Dropdown.jsx
- src/components/common/NE_Loader/CircularLoader.jsx
- src/components/common/NE_ToastMessage/index.jsx
- src/components/common/Rail/index.jsx
- src/pages/about/index.js
- src/styles/_default.scss
- src/styles/_keyframes.scss
- src/styles/globals.scss
- replace `Array.prototype.join(' ')` with util `cls` function for support multi classnames style
- separate the keyframes and default style from global
- none
- none
> refactor: support util function for multiple classnames

- package.json
> build: version bump upto v1.0.1

- src/components/common/NE_Badge/Badge.jsx
- src/components/common/NE_Badge/Badge.module.scss
- src/components/common/NE_Badge/index.js
- src/styles/_theme.scss
- src/types/FooterTypes.js
- src/utils/getVersion.js
- version number on footer 
- none
- none
> feat: add version number to footer

- src/components/common/NE_Badge/Badge.module.scss
- src/components/common/NE_Version/NE_Version.jsx
- src/types/FooterTypes.js
> feat: show node version in footer

- src/components/Header/Header.jsx
- src/components/Header/Navbar/Navbar.module.scss
> fix: menu page on mobile view

- src/components/Header/Navlinks/index.jsx
- src/types/NavbarTypes.js
- src/types/index.js
> feat: hide the dao on test net #203

- src/pages/_app.js
> fix: disable refetch of data on window focus

- .github/workflows/bump-version.yml
- .github/workflows/update-changelog.yml
- scripts/incrementMajor.js
- scripts/incrementMinor.js
- scripts/incrementPatch.js
- scripts/incrementVersion.js
> feat: automate version bump and changelog

- .github/workflows/bump-version.yml
- .github/workflows/update-changelog.yml
- scripts/incrementVersion.js
> ci: move to dev dependency 

- .github/workflows/bump-version.yml
> fix: add force push

- src/pages/_app.js
- src/pages/_error.js
- src/pages/about/index.js
- src/pages/blocks/index.js
- src/pages/dao/ambassador/index.js
- src/pages/dao/developer/index.js
- src/pages/dao/invoices/[username].js
- src/pages/globalnames/index.js
- src/pages/index.js
- src/pages/metrics/index.js
- src/pages/namespaces/index.js
- src/pages/richlist/index.js
- src/pages/scan/[addr].js
- src/pages/scan/index.js
- src/pages/test/index.js
- src/pages/tokens/index.js
- src/pages/transactions/index.js
- src/pages/trustlist/index.js
- src/utils/common/index.js
- src/utils/common/object.js
- src/utils/common/toKebabCase.js
- src/utils/index.js
> refactor: the layout of pages and separate from adding to globally

- src/components/Panel2/Panel2.jsx
- src/components/common/NE_Card/NE_DetailCard/DetailCard.module.scss
- src/components/common/NE_Card/NE_DetailCard/Market/index.jsx
- src/components/common/NE_Card/NE_DetailCard/index.jsx
-
- <img width="340" alt="Screenshot 2022-09-05 at 8 29 04 PM" src="https://user-images.githubusercontent.com/52356082/188477071-0d4dd475-d2eb-4e51-a28f-807505010ca3.png">
- <img width="309" alt="Screenshot 2022-09-05 at 8 28 25 PM" src="https://user-images.githubusercontent.com/52356082/188477100-53da0bb2-86bd-4d3e-a886-7003b7be0dc1.png">
- none
> feat: detail card active ticker style revamp

- src/components/Panel2/Panel2.jsx
- src/components/common/NE_Card/NE_DetailCard/Basic/Basic.module.scss
- src/components/common/NE_Card/NE_DetailCard/Basic/index.jsx
- src/components/common/NE_Card/NE_DetailCard/Market/index.jsx
- src/utils/common/index.js
- src/utils/common/number.js
- Returns only fixed number of digits for a given number 
- none
- none
> feat: market price number precision to 6 digits

- README.md
- src/components/UserAccount/TransactionDetails/TransactionDetails.jsx
- src/components/Views/Richlist/Richlist.jsx
> docs: add some badges to readme

- package.json
- yarn.lock
- update next, react and react-dom
- none
- none
> chore: update next, react and react-dom

- src/components/Panel3/Panel3.jsx
- src/components/common/NE_Card/NE_CompactCard/index.jsx
- src/components/common/NE_Card/NE_DetailCard/index.jsx
warn if there is no data to render
convert string the market value
-
- none
- none
> fix: passing boolean to class methods

- src/pages/scan/[addr].js
> fix: scan layout not showing

- src/components/common/NE_ErrorMessage/ErrorMessage.module.scss
- src/components/common/NE_ErrorMessage/index.jsx
- src/styles/globals.scss
> style: remove unused styles and rearrange

- .github/labeler.yml
- .github/pull_request_template.md
- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- .github/workflows/update-changelog.yml
- refactor pr template
- separate auto label and release drafter
- change commit message of update change-log actions
- remove old labeller check for files
- none
- none
> ci: improve template and labeler

- package.json
- src/components/HOC/PromiseLayout/index.jsx
- src/components/UserAccount/TransactionDetails/TransactionDetails.jsx
- src/components/Views/Dao/InvoiceTable/index.jsx
- src/components/Views/Richlist/Richlist.jsx
- src/components/Views/Trustlist/Trustlist.jsx
- src/pages/scan/[addr].js
- src/pages/scan/index.js
-  Create single component for the isLoading and isError 
- Provide all params for promise to resolve 
- none
- none
> feat: merge isLoading, isError to single component

- src/pages/scan/[addr].js
> fix: trust address scan error

- src/pages/scan/[addr].js
> fix: case when trust = 0

- .github/workflows/labeler.yml
- .github/workflows/release-drafter.yml
- .github/workflows/update-changelog.yml
- fix release draft generation 
- none
- none
> ci: fix relase drafter generation pr

- src/pages/scan/[addr].js
Merge pull request #265 from rayanfer32/develop## Description
-
-
- none
- none
> fix: case handle trust value being negative

- src/components/Views/About/About.jsx
-
- fix about page user contributor name 
- remove all the bot names
- none
- none
> fix: about page contributer

- src/components/Header/PageHeader/PageHeader.jsx
- src/pages/scan/tx.jsx
> refactor: reuse page header for meta data

- .editorconfig
- .github/CODEOWNERS
> ci: create CODEOWNERS

- src/components/Panel3/Panel3.jsx
- src/utils/helper.js
- Firefox browser was parsing date incorrectly 
-
- none
- none
> fix: invalid date issue with firefox

- src/components/TestComponents/index.jsx
- src/components/common/NE_Loader/CircularLoader.jsx
- src/components/common/NE_Loader/DotLoader.jsx
- src/components/common/NE_Loader/index.jsx
- src/components/common/NE_TabChanger/TabChanger.module.scss
- `http://localhost:3000/test` check it on
- new tab changer and SVG loader logo introduce 
**_NOTE: SVG LOADER STILL ON BETA STAGE_**
- none
- none
> feat: new svg loader implementation 

- src/components/Panel1/Panel1.jsx
- src/components/Panel2/Panel2.jsx
- src/types/DaoAccounts.js
> feat: shimmer-fallback

- src/hooks/useDarkMode/useDarkMode.js
> fix: global theme not set

- src/components/Panel1/Panel1.jsx
- src/components/Panel2/Panel2.jsx
> fix: check if value isInvalid instead of isNaN

- src/components/Views/GlobalNames/GlobalNames.jsx
- src/components/Views/Namespaces/Namespaces.jsx
- src/components/Views/Tokens/Tokens.jsx
- src/hooks/useNetwork/useNetwork.jsx
- src/pages/scan/index.js
> feat: show token , globalname and namespace details

- src/components/Panel1/Panel1.jsx
- src/components/Panel2/Panel2.jsx
- src/hooks/useNetwork/useNetwork.jsx
> fix: increase cache duration for ledger APIs

- src/styles/_mixins.scss
- width is overflowing on testnet
- style
- none
- none
> fix: expanded width for testnet

- src/components/UserAccount/TransactionDetails/TransactionDetails.jsx
- src/components/Views/Richlist/Richlist.jsx
- src/components/Views/Trustlist/Trustlist.jsx
> fix: sum all contract amounts

- src/components/common/NE_CopyText/CopyText.jsx
- src/styles/_fonts.scss
- src/styles/globals.scss
Use monospace font for addresses 
-
-
- none
- none
> feat: use monospace font for addresses

- package.json
- src/components/Panel3/Panel3.jsx
- src/components/common/NE_RTTable/NE_DateTime/DateTime.jsx
- src/pages/_app.js
- yarn.lock
> feat: show "4s ago" indicator instead of the UTC time on the RTT block

- src/components/common/InfoCard/InfoCard.module.scss
- src/components/common/InfoCard/index.jsx
> feat: show infocard count

- src/components/Views/Metrics/Metrics.jsx
- src/hooks/useNetwork/useNetwork.jsx
> feat: show total NXS on tritium in metrics page
